# Generated by Django 3.0 on 2019-12-08 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0002_auto_20191208_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rubric',
            name='url',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Только латинские буквы', regex='[zA-Z]')]),
        ),
    ]
