# Generated by Django 3.0 on 2019-12-08 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rubric',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Articles.Rubric'),
        ),
        migrations.AddField(
            model_name='comment',
            name='artcile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Articles.Article'),
        ),
    ]
