# Generated by Django 3.0 on 2019-12-08 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0005_auto_20191208_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='artcile',
            new_name='article',
        ),
        migrations.AlterField(
            model_name='rubric',
            name='url',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Только латинские буквы', regex='[a0-9-zA-Z]*$')]),
        ),
    ]
